# Generated by Django 3.1.2 on 2020-10-11 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('from_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.country')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.person')),
            ],
        ),
    ]
